var res = {
    door        : "res/door.png",
    boy         : "res/boy_2_3.png",
    conan       : "res/conan_4_4.png",
    enter       : "res/enter.png",
    grandma     : "res/grandma_1_5.png",
    greengiant  : "res/greengiant_1_1.png",
    hinada      : "res/hinada_5_1.png",
    jinzhengen  : "res/jinzhengen_2_5.png",
    lin         : "res/lin_3_4.png",
    mfc         : "res/mfc_2_5.png",
    momo        : "res/momo_4_3.png",
    naruto      : "res/naruto_5_5.png",
    outman      : "res/outman_5_4.png",
    saw         : "res/saw_1_3.png",
    snakewoman  : "res/snakewoman_2_2.png",
    title       : "res/title.png",
    wait        : "res/wait.png",
    yin         : "res/yin_2_3.png",
    yingmu      : "res/yingmu_4_2.png",
    zhijia      : "res/zhijia.png",
    font_futura : "res/fonts/Futura.ttc",
    process     : "res/process.png",
    newgame     : "res/newgame.png"
};
var g_resources = [
    //image
    res.door,
    res.title,
    res.zhijia,
    res.newgame,

    res.enter,
    res.wait,
    res.process,

    res.boy,
    res.conan,
    res.grandma,
    res.greengiant,
    res.hinada,
    res.jinzhengen,
    res.lin,
    res.mfc,
    res.momo,
    res.naruto,
    res.outman,
    res.saw,
    res.snakewoman,
    res.yin,
    res.yingmu
];